name: Hello World CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: |
          cat hello_world.txt

      - name: my_artifact
      run: |
        cat hello_world.txt > test_report.txt
        echo "All tests passed successfully" >> test_report.txt