name: Hello  CI/CD with Artifacts

on:
  push:
    branches:
      - main

jobs:
  build_step:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World with artifacts
        run: |
          cat timestamped_hello.txt

      - name: Generate my-artifact
        run: |
          echo "Hello, CI/CD World! Created at $(date)" > my-artifact.txt
          echo "All tests passed successfully" >> my-artifact.txt
    
      - name: Upload my-artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my-artifact.txt

  staging:
    runs-on: ubuntu-latest
    needs: build_step
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download my-artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
    
    - name: Display my-artifact
      run: cat my-artifact.txt

    
