name: Hello  CI/CD with Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Hello World with artifacts
        run: |
          cat timestamped_hello.txt

      - name: Generate my-artifact
        run: |
          cat timestamped_hello.txt > my-artifact.txt
          echo "All tests passed successfully" >> my-artifact.txt
    
      - name: Upload my-artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my-artifact.txt

